export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"

export const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING"
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS"
export const REQUEST_ROBOTS_FAILED = "REQUEST_ROBOTS_FAILED"

export const REQUEST_CHAMPS_PENDING = "REQUEST_CHAMPS_PENDING"
export const REQUEST_CHAMPS_SUCCESS = "REQUEST_CHAMPS_SUCCESS"
export const REQUEST_CHAMPS_FAILED = "REQUEST_CHAMPS_FAILED"